// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package memory

import (
	domain "github.com/alces-flight/concertim-mrapi/domain"
	"time"
)

type ConverterImpl struct{}

func (c *ConverterImpl) ConvertHost(source domain.Host) Host {
	var memoryHost Host
	memoryHost.Name = source.Name
	memoryHost.Reported = ConvertTime(source.Reported)
	memoryHost.TMax = time.Duration(source.TMax)
	memoryHost.DMax = time.Duration(source.DMax)
	return memoryHost
}
func (c *ConverterImpl) ConvertMetric(source domain.Metric) Metric {
	var memoryMetric Metric
	memoryMetric.Name = source.Name
	memoryMetric.Val = source.Val
	memoryMetric.Units = source.Units
	memoryMetric.Slope = domain.MetricSlope(source.Slope)
	memoryMetric.Tn = time.Duration(source.Tn)
	memoryMetric.TMax = time.Duration(source.TMax)
	memoryMetric.DMax = time.Duration(source.DMax)
	memoryMetric.Source = source.Source
	memoryMetric.Type = domain.MetricType(source.Type)
	return memoryMetric
}
