# This docker compose file is intended for developing
# concertim-metric-reporting-daemon.  It is *NOT* suitable for production
# usage.  See README.md for production installation instructions.

services:
  metrics: 
    build:
      context: .

    ports:
      - '3000:3000'

    command: ["air", "--", "--config-file", "/app/config/config.dev.yml"]

    # Mount `.` to `/app` to allow editing on the local and having flask automatically reload.
    volumes:
      - ./:/app

    # Use the same UID and GID as is used for the local user.  This prevents
    # issues with permissions for files in the mounted volume.
    #
    # If this setting is not suitable for you, use the
    # `docker-compose.override.yml` file to change it.  See
    # `docs/DEVELOPMENT.md` for details.
    # user: "1000:1000"
