// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package memory

import (
	domain "github.com/alces-flight/concertim-metric-reporting-daemon/domain"
	"time"
)

type ConverterImpl struct{}

func (c *ConverterImpl) DomainFromModelHost(source HostModel) domain.PendingHost {
	var domainPendingHost domain.PendingHost
	domainPendingHost.Id = domain.HostId(source.DeviceId)
	domainPendingHost.DSM = DSMNameToDSM(source.DSMName)
	domainPendingHost.Reported = ConvertTime(source.Reported)
	domainPendingHost.DMax = time.Duration(source.DMax)
	domainPendingHost.Metrics = DefaultMetrics()
	return domainPendingHost
}
func (c *ConverterImpl) DomainFromModelMetric(source MetricModel) domain.PendingMetric {
	var domainPendingMetric domain.PendingMetric
	domainPendingMetric.Name = source.Name
	domainPendingMetric.Value = source.Val
	domainPendingMetric.Units = source.Units
	domainPendingMetric.Slope = domain.MetricSlope(source.Slope)
	domainPendingMetric.Reported = ConvertTime(source.Reported)
	domainPendingMetric.TTL = time.Duration(source.DMax)
	domainPendingMetric.Type = domain.MetricType(source.Type)
	return domainPendingMetric
}
func (c *ConverterImpl) ModelFromDomainHost(source domain.PendingHost) HostModel {
	var memoryHostModel HostModel
	memoryHostModel.DeviceId = string(source.Id)
	memoryHostModel.DSMName = source.DSM.HostName
	memoryHostModel.Reported = ConvertTime(source.Reported)
	memoryHostModel.DMax = time.Duration(source.DMax)
	return memoryHostModel
}
func (c *ConverterImpl) ModelFromDomainMetric(source domain.PendingMetric) MetricModel {
	var memoryMetricModel MetricModel
	memoryMetricModel.Name = source.Name
	memoryMetricModel.Val = source.Value
	memoryMetricModel.Units = source.Units
	memoryMetricModel.Slope = domain.MetricSlope(source.Slope)
	memoryMetricModel.Reported = ConvertTime(source.Reported)
	memoryMetricModel.DMax = time.Duration(source.TTL)
	memoryMetricModel.Type = domain.MetricType(source.Type)
	return memoryMetricModel
}
