# Configuration suitable for running on your development laptop.  It uses fake,
# aka canned data instead of making requests to remote servcies.

# Configuration for the HTTP API.
api:
  # The address of the network interface to listen on.
  ip: "127.0.0.1"

  # The port to listen on.
  port: 3000

  # Timeout for server to process a request.
  #
  # Requires a number and unit, e.g., `60s` for sixty seconds or `1h10m20s` for
  # one hour ten minutes and twenty seconds.
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  timeout: 100ms

# Configuration for the gangali data source server.
gds:
  # The address of the network interface to listen on.
  ip: "127.0.0.1"

  # The port to listen on.
  port: 8678

  # The cluster name to use in the ganglia output.
  clusterName: "unspecified"

  # The source to use in the ganglia output.
  metricSource: "ct-metric-reporting-daemon"

  # The time in seconds that a host should remain "fresh" for.
  #
  # If the last metric for a host was reported more than `hostTTL` seconds
  # ago, the host and all of its metrics are considered stale and no longer
  # included in the metric stream.
  hostTTL: 180

# Configuration for generating the data source map lookup.
dsm:
  # The data source map is periodically updated from the Concertim
  # Visualisation App. `frequency` specifies the frequency of the periodic
  # updating.
  #
  # Certain events can cause the data source map to update outside of its
  # periodic updating.  To prevent over consumption of resources, the updates
  # can be throttled such that no two updates will occur within `throttle` of
  # each other.
  #
  # Both the `frequency` and `throttle` values require a number and unit, e.g.,
  # `60s` for sixty seconds or `1h10m20s` for one hour ten minutes and twenty
  # seconds.
  #
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  frequency: 30s
  throttle: 10s

  # Estimate of how long it takes for the updater to run.
  #
  # If the DSM needs updating outside of its periodic updating, (for instance
  # when receiving a request to report a metric), the updating goroutine sleeps
  # for this duration and assumes that the update will have completed in that
  # duration.
  #
  # This adds a delay of `duration` to API calls to report a metric when the
  # host is not yet known.
  #
  # If this values is too small, it may temporarily result in metrics being
  # incorrectly rejected due to an unknown host.  Those metrics will eventually
  # be accepted.
  duration: 75ms

  # If this values is given and is not an empty string, the data source map
  # will be read from this file instead of polling the Concertim Visualisation
  # App. Relative paths are relative to the working directory of the running
  # process.
  testdata: "./testdata/dsm.json"

# Configuration for retrieving metrics from gmetad.
retrieval:
  # The IP address, or hostname, of the gmetad server to poll for metrics.
  ip: localhost

  # The port of the gmetad server to poll for metrics.
  port: 8651

  # The ganglia grid from which to retrieve clusters.  All other grids are
  # ignored.
  gridName: "unspecified"

  # The ganglia cluster from which to retrieve hosts.  All other clusters are
  # ignored.
  clusterName: "unspecified"

  # The metrics are periodically retrieved from the gmetad source. `frequency`
  # specifies the frequency of the periodic updating.
  #
  # Certain events can cause the metrics to be retrieved outside of its
  # periodic updating.  To prevent over consumption of resources, the updates
  # can be throttled such that no two updates will occur within `throttle` of
  # each other.
  #
  # Both the `frequency` and `throttle` values require a number and unit, e.g.,
  # `60s` for sixty seconds or `1h10m20s` for one hour ten minutes and twenty
  # seconds.
  #
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  frequency: 30s
  throttle: 10s

  # After gmetad has requested metrics from us, we request metrics from gmetad.
  # This value configures the delay between the two.  We want to provide enough
  # time for gmetad to have processed the metrics, but don't want to wait too
  # long as we want the metrics to be available to IRV as soon as possible.
  post_gmetad_delay: 500ms

  # If this values is given and is not an empty string, the ganglia XML will be
  # read from this file instead of polling the gmetad server.  In this case the
  # IP and port will be ignored.  Relative paths are relative to the working
  # directory of the running process.
  # testdata: "./testdata/ganglia-small.xml"
  testdata: "./testdata/ganglia.xml"

# Configuration for storing the processed results.
#
# Currently there is an expectation that the results will be stored in Memcache
# using the Ruby Marshal serialization format.  Golang has poor support for
# serializing and de-serializing Ruby Marshal, so we use a Ruby script to do
# this instead.  The Ruby script is supplied with the processed results as JSON
# via stdin.
recorder:
  # The path of an executable script that reads JSON from stdin in and saves
  # the results to Memcache using Ruby Marshal to serialize.
  path: "./libexec/results-to-memcache-faker.rb"
  # CLI args passed to the above script.  The first arg is the memcache address.
  args: ["localhost:11211"]

visualizerAPI:
  authUrl: "https://localhost:9445/users/sign_in.json"
  username: "admin"
  password: "admin"
  data_source_map_url: "https://localhost:9445/api/v1/data-source-maps"
  # If set to true skip all TLS certificate verification checks.
  skip_certificate_check: true

log_level: info
shared_secret_file: "./testdata/secret.dev"
