# Configuration for the HTTP API.
api:
  # The address of the network interface to listen on.
  ip: "0.0.0.0"

  # The port to listen on.
  port: 3000

  # Timeouts for server to process a request.
  #
  # read_timeout limits the time that the server will spend waiting for the
  # client to send its full request.
  #
  # write_timeout limits the time that the server will spend waiting for itself
  # to finish serving the request.
  #
  # idle_timeout limits the time before the server reuses keep alive
  # connections.
  #
  # Requires a number and unit, e.g., `60s` for sixty seconds or `1h10m20s` for
  # one hour ten minutes and twenty seconds.
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  read_timeout: 100ms
  write_timeout: 10s
  idle_timeout: 120s

# Configuration for generating the data source map lookup.
dsm:
  # The data source map is periodically updated from the Concertim
  # Visualisation App. `frequency` specifies the frequency of the periodic
  # updating.
  #
  # Certain events can cause the data source map to update outside of its
  # periodic updating.  To prevent over consumption of resources, the updates
  # can be throttled such that no two updates will occur within `throttle` of
  # each other.
  #
  # Both the `frequency` and `throttle` values require a number and unit, e.g.,
  # `60s` for sixty seconds or `1h10m20s` for one hour ten minutes and twenty
  # seconds.
  #
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  frequency: 30s
  throttle: 5s

# Configuration for accessing the Concertim Visualization App (aka Visualizer)
# API.
visualizer_api:
  # The URL used for gaining an authentication token.
  auth_url: "http://visualisation:7000/users/sign_in.json"
  # The authentication credentials.
  username: "admin"
  password: "admin"
  # The URL used to obtain the data source maps.
  data_source_map_url: "http://visualisation:7000/api/v1/data-source-maps"
  # If set to true skip all TLS certificate verification checks.
  skip_certificate_check: true

# Configuration for storing and retrieving historic metrics with RRDTool.
rrd:
  # The grid from which to retrieve historic metrics.
  # DEPRECATED.
  grid_name: "unspecified"

  # The cluster from which to retrieve historic metrics.
  # DEPRECATED.
  cluster_name: "unspecified"

  # Directory where the RRD files are stored.
  directory: /var/lib/metric-reporting-daemon/rrds/

  # Path to the RRDTool executable.
  rrd_tool_path: /usr/bin/rrdtool

  # How frequently metrics are reported to this daemon.
  step: 15s

log_level: info
log_file: /app/log/metric-reporting-daemon.log
shared_secret_file: "/opt/concertim/etc/secret"
