# Configuration for the HTTP API.
api:
  # The address of the network interface to listen on.
  ip: "0.0.0.0"

  # The port to listen on.
  port: 3000

# Configuration for the gangali data source server.
gds:
  # The address of the network interface to listen on.
  ip: "127.0.0.1"

  # The port to listen on.
  port: 8678

  # The cluster name to use in the ganglia output.
  clusterName: "unspecified"

  # The source to use in the ganglia output.
  metricSource: "ct-metric-reporting-daemon"

  # The time in seconds that a host should remain "fresh" for.
  #
  # If the last metric for a host was reported more than `hostTTL` seconds
  # ago, the host and all of its metrics are considered stale and no longer
  # included in the metric stream.
  hostTTL: 180

# Configuration for generating the data source map lookup.
dsm:
  # The type of retriever to use for obtaining the data source map look up
  # table.  Either "file" or "script".
  #
  # If "file", "path" should be set to the path to a JSON file containing an
  # object with device names as the keys and the device's map to host as the
  # value, e.g.,
  #
  #   {"comp001": "comp001.concertim.alces-flight.com", ...}
  #
  # If "script" it should be set to the path of an executable script that
  # prints JSON to stdout in the same format as above.
  retriever: "script"

  # See "retriever" comment for what this means.
  path: "/data/private/share/daemons/ct-metric-reporting-daemon/libexec/device-name-to-data_source_map.rb"

  # The data source map is periodically updated using the configured
  # retriever.  This value sets the time to sleep between runs.
  #
  # A valid entry requires a number and unit, e.g., `60s` for sixty seconds or
  # `1h10m20s` for one hour ten minutes and twenty seconds.
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  sleep: 30s

log_level: info
shared_secret_file: "/data/private/share/daemons/ct-metric-reporting-daemon/config/secret"
