# Configuration for retrieving metrics from gmetad.
gmetad:
  # The URL locating the gmetad server to poll for metrics.
  #
  # Typically, this will be "tcp://localhost:8651".
  #
  # Whilst developing a "file:" URL such as "file:./testdata/ganglia.xml" might
  # be useful.
  #
  # url: "file:./testdata/ganglia.xml"
  # url: "file:/home/ben/projects/concertim/src/daemons/ct-metric-processing-daemon/testdata/ganglia.xml"
  # url: "file:///home/ben/projects/concertim/src/daemons/ct-metric-processing-daemon/testdata/ganglia.xml"
  url: "./testdata/ganglia.xml"
  # url: "tcp://localhost:8651"

  # The metrics are periodically retrieved from the gmetad source.  This is the
  # minimum duration to sleep between polls.
  #
  # A valid entry requires a number and unit, e.g., `60s` for sixty seconds or
  # `1h10m20s` for one hour ten minutes and twenty seconds.
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  sleep: 10s

log_level: debug
