# Configuration for retrieving metrics from gmetad.
retrieval:
  # The IP address, or hostname, of the gmetad server to poll for metrics.
  ip: localhost

  # The port of the gmetad server to poll for metrics.
  port: 8651

  # The metrics are periodically retrieved from the gmetad source.  This is the
  # minimum duration to sleep between polls.
  #
  # A valid entry requires a number and unit, e.g., `60s` for sixty seconds or
  # `1h10m20s` for one hour ten minutes and twenty seconds.
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  sleep: 15s

# Configuration for storing the processed results.
#
# Currently there is an expectation that the results will be stored in Memcache
# using the Ruby Marshal serialization format.  Golang has poor support for
# serializing and de-serializing Ruby Marshal, so we use a Ruby script to do
# this instead.  The Ruby script is supplied with the processed results as JSON
# via stdin.
recorder:
  # The path of an executable script that reads JSON from stdin in and saves
  # the results to Memcache using Ruby Marshal to serialize.
  path: "/data/private/share/daemons/ct-metric-processing-daemon/libexec/results-to-memcache.rb"

# Configuration for obtaining the data source map.
#
# The data source map specifies how to map from a ganglia identifier triplet,
# e.g., "unspecified/unspecified/node001" to a concertim device identifier,
# e.g., "hacor:device:2".
dsm:
  # The type of retriever to use for obtaining the data source map look up
  # table.  Either "file" or "script".
  #
  # If "file", "path" should be set to the path to a JSON file containing an
  # object with grid names as keys and the values should be an object with
  # cluster names as keys and the values should be an object with device names
  # as keys and the device's memcache key as value.
  # E.g.,
  #
  #   {"unspecified": {"unspecified": {"comp001": "hacor:device:2", ...}}}
  #
  # If "script" it should be set to the path of an executable script that
  # prints JSON to stdout in the same format as above.
  retriever: "script"

  # See "retriever" comment for what this means.
  path: "/data/private/share/daemons/ct-metric-processing-daemon/libexec/dsm-to-memcache-key.rb"

log_level: info
