# Configuration for retrieving metrics from gmetad.
retrieval:
  # The IP address, or hostname, of the gmetad server to poll for metrics.
  ip: localhost

  # The port of the gmetad server to poll for metrics.
  port: 8651

  # The metrics are periodically retrieved from the gmetad source.  This is the
  # minimum duration to sleep between polls.
  #
  # A valid entry requires a number and unit, e.g., `60s` for sixty seconds or
  # `1h10m20s` for one hour ten minutes and twenty seconds.
  # Valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”.
  sleep: 10s

  # If this values is given and is not an empty string, the ganglia XML will be
  # read from this file instead of polling the gmetad server.  In this case the
  # IP add port will be ignored.  Relative paths are relative to the working
  # directory of the running process.
  testdata: "./testdata/ganglia.xml"

log_level: debug
