on:
  push:
    branches: "*"
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: "*"
    paths-ignore:
      - 'docs/**'

name: Lint
jobs:
  golangci:
    name: lint

    runs-on: ubuntu-22.04

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: golangci-lint command line arguments.
          #args:
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
