on:
  push:
    branches: "*"
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: "*"
    paths-ignore:
      - 'docs/**'

name: Build
jobs:
  build:

    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      # - uses: actions/cache@v3.0.5
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
